name: 特性请求
description: 请求一个不与基金委官方Word预设相冲突且能增强模版易用性或功能性的新特性
body:
  - type: checkboxes
    attributes:
      label: 前提条件
      options:
        - label: 确定当前使用的是[最新的模版](https://github.com/MGG1996/NSFC/releases/latest)。
          required: true
        - label: 已仔细查阅了基金委的官方Word模版，且确定该特性不违背其要求。
          required: true
        - label: 已仔细阅读了模版提供的[使用说明](https://github.com/MGG1996/NSFC/blob/main/readme.md)和[示例文档](https://github.com/MGG1996/NSFC/blob/main/tutorial.pdf)，且确定模版尚未提供此特性。
          required: true
        - label: 已浏览[待解决issue](https://github.com/MGG1996/NSFC/issues)和[已关闭issue](https://github.com/MGG1996/NSFC/issues?q=is%3Aissue%20state%3Aclosed)列表，且并未发现类似请求。
          required: true
  - type: textarea
    attributes:
      label: 描述一下该特性
      description: 请不要在同一个issue下提交多个不相关的特性请求。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 附加信息
      description: 如果你还有其他需要提供的信息，可以在这里填写。
